// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPeliculas.API.Migrations
{
    [DbContext(typeof(BlogPeliculasContext))]
    [Migration("20230521023713_AgregadoSeeder")]
    partial class AgregadoSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("BlogPeliculas.Modelos.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contenido")
                        .HasColumnType("TEXT");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Recomendar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.ToTable("Comentarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contenido = "¡Es una película muy divertida!",
                            PeliculaId = 1,
                            Recomendar = true
                        },
                        new
                        {
                            Id = 2,
                            Contenido = "¡Me encantó la trama!",
                            PeliculaId = 1,
                            Recomendar = true
                        },
                        new
                        {
                            Id = 3,
                            Contenido = "¡La volvere a ver!",
                            PeliculaId = 1,
                            Recomendar = true
                        },
                        new
                        {
                            Id = 4,
                            Contenido = "¡Asombroso!",
                            PeliculaId = 2,
                            Recomendar = true
                        },
                        new
                        {
                            Id = 5,
                            Contenido = "¡Me encantó!",
                            PeliculaId = 2,
                            Recomendar = true
                        },
                        new
                        {
                            Id = 6,
                            Contenido = "Me gusto los personajes pero no la trama.",
                            PeliculaId = 2,
                            Recomendar = false
                        },
                        new
                        {
                            Id = 7,
                            Contenido = "¡Es una película muy divertida!",
                            PeliculaId = 3,
                            Recomendar = true
                        },
                        new
                        {
                            Id = 8,
                            Contenido = "¡Me encantó la trama!",
                            PeliculaId = 3,
                            Recomendar = true
                        },
                        new
                        {
                            Id = 9,
                            Contenido = "¡Es una película muy divertida!",
                            PeliculaId = 5,
                            Recomendar = true
                        });
                });

            modelBuilder.Entity("BlogPeliculas.Modelos.Pelicula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnCines")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEstreno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnCines = true,
                            FechaEstreno = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Super Mario Bros.: La película"
                        },
                        new
                        {
                            Id = 2,
                            EnCines = false,
                            FechaEstreno = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Doctor Strange: En el multiverso de la locura"
                        },
                        new
                        {
                            Id = 3,
                            EnCines = true,
                            FechaEstreno = new DateTime(2022, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "The Batman"
                        },
                        new
                        {
                            Id = 4,
                            EnCines = false,
                            FechaEstreno = new DateTime(2023, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "The Flash"
                        },
                        new
                        {
                            Id = 5,
                            EnCines = true,
                            FechaEstreno = new DateTime(2021, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Titulo = "Venom: Habrá matanza"
                        });
                });

            modelBuilder.Entity("BlogPeliculas.Modelos.Personaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeliculaId");

                    b.ToTable("Personajes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Mario",
                            PeliculaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Luigi",
                            PeliculaId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Peach",
                            PeliculaId = 1
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Bowser",
                            PeliculaId = 1
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Doctor Strange",
                            PeliculaId = 2
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Bruja Escarlata",
                            PeliculaId = 2
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Batman",
                            PeliculaId = 3
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Flash",
                            PeliculaId = 4
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Venom",
                            PeliculaId = 5
                        });
                });

            modelBuilder.Entity("BlogPeliculas.Modelos.Comentario", b =>
                {
                    b.HasOne("BlogPeliculas.Modelos.Pelicula", "Pelicula")
                        .WithMany("Comentarios")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("BlogPeliculas.Modelos.Personaje", b =>
                {
                    b.HasOne("BlogPeliculas.Modelos.Pelicula", "Pelicula")
                        .WithMany("Personjes")
                        .HasForeignKey("PeliculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pelicula");
                });

            modelBuilder.Entity("BlogPeliculas.Modelos.Pelicula", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Personjes");
                });
#pragma warning restore 612, 618
        }
    }
}
