// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpresaUTN.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EmpresaUTN.Modelos.Canton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CabeceraCantonal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Cantones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CabeceraCantonal = "Distrito Metropolitano de Quito",
                            Nombre = "Quito",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 2,
                            CabeceraCantonal = "Guayaquil",
                            Nombre = "Guayaquil",
                            ProvinciaId = 2
                        },
                        new
                        {
                            Id = 3,
                            CabeceraCantonal = "Tulcan",
                            Nombre = "Tulcan",
                            ProvinciaId = 3
                        },
                        new
                        {
                            Id = 4,
                            CabeceraCantonal = "Ibarra",
                            Nombre = "Ibarra",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 5,
                            CabeceraCantonal = "La Libertad",
                            Nombre = "La Libertad",
                            ProvinciaId = 5
                        },
                        new
                        {
                            Id = 6,
                            CabeceraCantonal = "Otavalo",
                            Nombre = "Otavalo",
                            ProvinciaId = 4
                        },
                        new
                        {
                            Id = 7,
                            CabeceraCantonal = "Tabacundo",
                            Nombre = "Pedro Moncayo",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 8,
                            CabeceraCantonal = "Quito",
                            Nombre = "Quito Sur",
                            ProvinciaId = 1
                        },
                        new
                        {
                            Id = 9,
                            CabeceraCantonal = "Cotacachi",
                            Nombre = "Cotacachi",
                            ProvinciaId = 4
                        });
                });

            modelBuilder.Entity("EmpresaUTN.Modelos.Pais", b =>
                {
                    b.Property<int>("CodigoPais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Capital")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Poblacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("CodigoPais");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            CodigoPais = 1,
                            Capital = "Quito",
                            CodigoISO = "EC",
                            Idioma = "Español",
                            Moneda = "USD",
                            Nombre = "Ecuador",
                            Poblacion = 17643054
                        },
                        new
                        {
                            CodigoPais = 2,
                            Capital = "Buenos Aires",
                            CodigoISO = "AR",
                            Idioma = "Español",
                            Moneda = "ARS",
                            Nombre = "Argentina",
                            Poblacion = 44938712
                        });
                });

            modelBuilder.Entity("EmpresaUTN.Modelos.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActividadEconomica")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Area")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaisCodigoPais")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaisCodigoPais");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActividadEconomica = "Agricultura",
                            Area = 10487,
                            Nombre = "Pichincha",
                            PaisCodigoPais = 1
                        },
                        new
                        {
                            Id = 2,
                            ActividadEconomica = "Pesca",
                            Area = 15480,
                            Nombre = "Guayas",
                            PaisCodigoPais = 1
                        },
                        new
                        {
                            Id = 3,
                            ActividadEconomica = "Ganaderia",
                            Area = 3800,
                            Nombre = "Carchi",
                            PaisCodigoPais = 1
                        },
                        new
                        {
                            Id = 4,
                            ActividadEconomica = "Turismo",
                            Area = 4600,
                            Nombre = "Imbabura",
                            PaisCodigoPais = 1
                        },
                        new
                        {
                            Id = 5,
                            ActividadEconomica = "Agricultura",
                            Area = 307571,
                            Nombre = "Buenos Aires",
                            PaisCodigoPais = 2
                        });
                });

            modelBuilder.Entity("EmpresaUTN.Modelos.Canton", b =>
                {
                    b.HasOne("EmpresaUTN.Modelos.Provincia", "Provincia")
                        .WithMany("Cantones")
                        .HasForeignKey("ProvinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("EmpresaUTN.Modelos.Provincia", b =>
                {
                    b.HasOne("EmpresaUTN.Modelos.Pais", "Pais")
                        .WithMany("Provincias")
                        .HasForeignKey("PaisCodigoPais")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("EmpresaUTN.Modelos.Pais", b =>
                {
                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("EmpresaUTN.Modelos.Provincia", b =>
                {
                    b.Navigation("Cantones");
                });
#pragma warning restore 612, 618
        }
    }
}
